name       : haskell-void
version    : 0.7.2
release    : 2
source     :
    - https://hackage.haskell.org/package/void-0.7.2/void-0.7.2.tar.gz : d3fffe66a03e4b53db1e459edf75ad8402385a817cae415d857ec0b03ce0cf2b
license    : BSD-3-Clause
component  : programming.haskell
summary    : A Haskell 98 logically uninhabited data type, used to indicate that a given term should not exist.
description: |
    A Haskell 98 logically uninhabited data type, used to indicate that a given term should not exist.
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register

