name       : haskell-void
version    : 0.7.1
release    : 1
source     :
    - http://hackage.haskell.org/package/void-0.7.1/void-0.7.1.tar.gz : c9f0fd93680c029abb9654b5464be260652829961b18b7046f96a0df95e825f4
license    : BSD-3-Clause
component  : programming.haskell
summary    : A Haskell 98 logically uninhabited data type, used to indicate that a given term should not exist.
description: |
    A Haskell 98 logically uninhabited data type, used to indicate that a given term should not exist.
builddeps  :
    - haskell-cabal-install
    - haskell-semigroups
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register

