name       : haskell-void
version    : 0.7.3
release    : 3
source     :
    - https://hackage.haskell.org/package/void-0.7.3/void-0.7.3.tar.gz : 53af758ddc37dc63981671e503438d02c6f64a2d8744e9bec557a894431f7317
license    : BSD-3-Clause
component  : programming.haskell
summary    : A Haskell 98 logically uninhabited data type, used to indicate that a given term should not exist.
description: |
    A Haskell 98 logically uninhabited data type, used to indicate that a given term should not exist.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register

